### Base URL
@baseUrl = http://localhost:8080/cloud
@contentType = application/json
#@authToken = {{login.response.body.authToken}}

### 1. Регистрация нового пользователя
# @name register
POST {{baseUrl}}/register
Content-Type: {{contentType}}

{
  "login": "testuser@example.com",
  "password": "TestPass123!"
}

### 2. Логин пользователя
# @name login
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "login": "testuser@example.com",
  "password": "TestPass123!"
}

### 3. Логин с неверными credentials
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "login": "wronguser",
  "password": "wrongpass"
}

### 4. Проверка валидности токена (ЗАМЕНИТЕ на реальный токен из шага 2)
GET {{baseUrl}}/list?limit=1
Authorization: Bearer ec5a4690-8395-4bd1-88dd-d091875abd9e
Content-Type: {{contentType}}

### 4. Загрузка файла
POST {{baseUrl}}/file?filename=test-file.txt
Authorization: Bearer ec5a4690-8395-4bd1-88dd-d091875abd9e
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-file.txt"
Content-Type: text/plain


### 5. Получение списка файлов (требует авторизации)
GET {{baseUrl}}/list?limit=10
Authorization: Bearer ec5a4690-8395-4bd1-88dd-d091875abd9e
Content-Type: {{contentType}}

### 6. Скачивание файла (требует авторизации)
GET {{baseUrl}}/file?filename=test-file.txt
Authorization: Bearer ec5a4690-8395-4bd1-88dd-d091875abd9e
Accept: application/octet-stream

### 7. Переименование файла (требует авторизации)
PUT {{baseUrl}}/file?filename=test-file.txt&newFilename=renamed-file.txt
Authorization: Bearer 81723d6f-89a7-41c1-8c20-f373665e7a35
Content-Type: {{contentType}}


### 8. Удаление файла (требует авторизации)
DELETE {{baseUrl}}/file?filename=renamed-file.txt
Authorization: Bearer 81723d6f-89a7-41c1-8c20-f373665e7a35
Content-Type: {{contentType}}

### 9. Выход из системы (требует авторизации)
POST {{baseUrl}}/logout
Authorization: Bearer cdf5880f-95c9-4f08-98b3-c6280c4917da
Content-Type: {{contentType}}

### 10. OPTIONS запрос для CORS проверки
OPTIONS {{baseUrl}}/login
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Origin: http://localhost:8081

### 11. Проверка здоровья приложения
GET {{baseUrl}}/actuator/health

### 12. Получение информации о приложении
GET {{baseUrl}}/actuator/info

### 13. Тест с неверным токеном (401)
GET {{baseUrl}}/list
Authorization: Bearer 5ead8849-0033-4b1a-9cb4-f7bc1659fbb4
Content-Type: {{contentType}}

### 14. Тест без токена (401)
GET {{baseUrl}}/list
Content-Type: {{contentType}}

### 15. Регистрация второго пользователя
POST {{baseUrl}}/register
Content-Type: {{contentType}}

{
  "login": "anotheruser@example.com",
  "password": "AnotherPass123!"
}

### 16. Логин второго пользователя
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "login": "anotheruser@example.com",
  "password": "AnotherPass123!"
}