services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: clouddb
      POSTGRES_USER: clouduser
      POSTGRES_PASSWORD: cloudpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U clouduser -d clouddb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/clouddb
      SPRING_DATASOURCE_USERNAME: clouduser
      SPRING_DATASOURCE_PASSWORD: cloudpass
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
    volumes:
      - file_storage:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  file_storage:
